<?php

/**
* Autor: Josué Barros da Silva
* Website: joshuawebdev.wordpress.com
* Email: josue.barros1986@gmail.com
* Versão 1.0 (versão de teste)
*
* Inicialmente o programa lê uma string no formato csv que é a
* primeira linha de um arquivo que contém os dados de uma tabela
* e transforma a string para o formato json
*
*/

// inicia a string abrindo um array no formato json
$json = "[\n  ";

$head_csv = "CODIGO;MATRICULA;DTINICIO;ALUNO;ANACIONAL;ANATUAL;SEXO;REGISTRO;LIVRO;FOLHA;DTREGISTRO;CARTORIO;PROCEDENCIA;NASCIMENTO;NAUF;AUTORIZA;BOLSA;AENDERECO;ABAIRRO;ACIDADE;AUF;ACEP;ALOCAL;ORELIGIAO;RELIGIAO;ATELEFONE;OBSPREF;CODSIT;DATASIT;PAI;PNACIONAL;PNATURAL;PPROFISSAO;PFONE;PENDTRABALHO;MAE;MPROFISSAO;MNATURAL;MNACIONAL;MFONE;MENDTRABALHO;PRENDA;MRENDA;RESPONSAVEL;RPROFISSAO;RNATURAL;RNACIONAL;RENDERECO;RRENDA;RFONE;ASMA;BRONQUITE;DIABETES;EPLEPSIA;HIPERTENSAO;REUMATISMO;OUTDOENCA;DFISICA;DAUDITIVA;DVISUAL;DFALA;OUTDEFICIENCIA;CATAPORA;CAXUMBA;COQUELUCHE;ESCARLATINA;RUBEOLA;SARAMPO;OUTCONTAGIOSA;PLANODESAUDE;EMCASODEFEBRE;ALERGIAS;REALIZANDOTRATAMENTO;ENOME;EFONE;EMEDICO;EMEDFONE;EHOSPITAL;EHOSFONE;BCGORAL;BCGINTRA;ANTITIFO;TRIPLICE;OUTVACINA;SABIM;AVARIOLA;ASARAMPO;FILENAME;RRG;RCPF;REMAIL;ARG;ARGEMISS;ALIAS;ACPF;ACOMPLETO;ANUM";

// substitui os ; por quebra de linha e salva isso em $rotulo_json
$rotulo_json = preg_replace( "/;/", "\n    ", $head_csv );

$json .= "{\n    {$rotulo_json}\n  }\n]\n";

echo "\n".$json;

?>
